name: test_restraints
data_path: restraint_test
tier: 1

jobs:
    linear:

        strategy:
            distance: [0.0, 1.0]
            target: [0, 20, 60]
            ref: [99, 50]

        steps:
             run2: polyply gen_params -seq PEO:100 -o test.itp -name test -lib martini3
             run3: setup_top_file -o test.top -ff-dir martini3 -ff-file martini_v3.0.0.itp -itps "test.itp" -mols test:1
             run4: setup_build_file -restr test:0:1:{ref}_{target}_{distance}
             run5: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 10 10 10 -b build_file.bld
             #run6: satisfy_constraints -c test.gro -p test.top -name test

    comb:

        strategy:
            # the comb branches have indices > 99
            # branches are 10 each
            # {100, 101, 102, 103, 104, 105, 106, 107, 108, 109},
            # {110, 111, 112, 113, 114, 115, 116, 117, 118, 119},
            # {120, 121, 122, 123, 124, 125, 126, 127, 128, 129},
            # {130, 131, 132, 133, 134, 135, 136, 137, 138, 139},
            # {140, 141, 142, 143, 144, 145, 146, 147, 148, 149},
            # {150, 151, 152, 153, 154, 155, 156, 157, 158, 159},
            # {160, 161, 162, 163, 164, 165, 166, 167, 168, 169},
            # {170, 171, 172, 173, 174, 175, 176, 177, 178, 179},
            # {180, 181, 182, 183, 184, 185, 186, 187, 188, 189},
            # {190, 191, 192, 193, 194, 195, 196, 197, 198, 199}]

            distance: [0.0, 1.0]
            ref: [0, 50]
            target: [99, 25]

        steps:
             run2: polyply gen_params -seqf {data_path}/comb.json -o test.itp -name test -lib martini3
             run3: setup_top_file -o test.top -ff-dir martini3 -ff-file martini_v3.0.0.itp -itps test.itp -mols test:1
             run4: setup_build_file -restr test:0:1:{ref}_{target}_{distance}
             run5: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 10 10 10 -b build_file.bld
             #run6: satisfy_constraints -c test.gro -p test.top -name test

    cycle:
        strategy:
            monomers: [10, 100]
        steps:
             run1: polyply gen_params -seq PEO:{monomers} -o test.itp -name test -lib martini3
             run2: setup_top_file -o test.top -ff-dir martini3 -ff-file martini_v3.0.0.itp -itps "test.itp" -mols test:1
             run3: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 10 10 10 -cycles test
