name: template_generation
data_path: templates
tier: 1

jobs:
    AMBER:

        strategy:
            residue: ["DG", "DA", "DT", "DC"]

        steps:
             run1: polyply gen_params -seq {residue}:1 -o test.itp -name test -lib parmbsc1
             run2: setup_top_file -o test.top -ff-dir amber14sb_parmbsc1.ff -ff-file forcefield.itp -itps "test.itp" -mols test:1
             run3: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 3. 3. 3.
             run4: satisfy_geometry -c test.gro -p test.top -name test

    2016H66:

        strategy:
            residue: ["HEA", "PAM", "PE", "PEO", "PMMA", "PMA", "PP", "PS", "PVA"]

        steps:
             run1: polyply gen_params -seq {residue}:1 -o test.itp -name test -lib 2016H66
             run2: setup_top_file -o test.top -ff-dir 2016H66.ff -ff-file forcefield.itp -itps "test.itp" -mols test:1
             run3: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 3. 3. 3.
             run4: satisfy_geometry -c test.gro -p test.top -name test
