name: test_template_generation
data_path: template_test

jobs:
    AMBER:

        strategy:
            residue: ["DG", "DA"]

        steps:
             run1: polyply gen_params -seq {residue}:1 -o test.itp -name test -lib parmbsc1
             run2: setup_top_file -o test.top -ff-dir amber14sb_parmbsc1.ff -ff-file forcefield.itp -itps "test.itp" -mols test:1
             run3: polyply gen_coords -o test.gro -p test.top -name test -back_fudge 1 -box 3. 3. 3.
             run4: satisfy_geometry -c test.gro -p test.top -name test
