name: genome
data_path: genome
tier: 3

jobs:
    PARMBSC:

        strategy:

        steps:
            run1: polyply gen_params -lib parmbsc1 -seqf {data_path}/DNA_seq.json -o csDNA.itp -name csDNA
            run2: setup_top_file -o system.top -ff-dir amber14sb_parmbsc1.ff -ff-file forcefield.itp\
                  -itps csDNA.itp {data_path}/protein.itp {ff_path}/tip3.itp -mols test:1

            run2: polyply gen_coords -p {data_path}/build.top -b {data_path}/build_file.bld -o test.gro -cycles csDNA -name test\
                  -box 23.62 23.62 23.62 -nr 20 -cycle_tol 0.8 -res DA DG DT DC SOL NA -lig csDNA#60:NA -c {data_path}/capsid.gro

            run3: gmx grompp -f {data_path}/min.mdp -c test.gro -p {data_path}/topol.top -o min.tpr -r test.gro
            run4: gmx mdrun -v -deffnm min -s min.tpr -nt 1
